//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aymk_database.Database
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using System.Runtime.Serialization;
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Alert = new HashSet<Alert>();
            this.Exchange = new HashSet<Exchange>();
            this.Log = new HashSet<Log>();
            this.Notification = new HashSet<Notification>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string phoneNumber { get; set; }
        public Nullable<bool> alertEmail { get; set; }
        public Nullable<bool> alertNotification { get; set; }
        public Nullable<bool> alertSms { get; set; }
        public Nullable<bool> tradeEmail { get; set; }
        public Nullable<bool> tradeNotification { get; set; }
        public Nullable<bool> tradeSms { get; set; }
        public Nullable<System.DateTime> lastLogin { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public string deviceModel { get; set; }
        public string deviceType { get; set; }
        public string devicePrivateKey { get; set; }
        public string devicePublicKey { get; set; }
        public string devicePlayerId { get; set; }
        public Nullable<bool> active { get; set; }
    
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	 
    	    
        public virtual ICollection<Alert> Alert { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	 
        public virtual ICollection<Exchange> Exchange { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	 
    	    
        public virtual ICollection<Log> Log { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
     
    	    
        public virtual ICollection<Notification> Notification { get; set; }
    }
}
