//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aymk_database.Database
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using System.Runtime.Serialization;
    public partial class Alert
    {
        public long id { get; set; }
        public int accountId { get; set; }
        public int marketId { get; set; }
        public int valueType { get; set; }
        public decimal savedValue { get; set; }
        public decimal belowValue { get; set; }
        public decimal aboveValue { get; set; }
        public bool isPersistent { get; set; }
        public string alertComment { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> updateAt { get; set; }
        public bool active { get; set; }
    
        public virtual CatalogMarket CatalogMarket { get; set; }
        public virtual Account Account { get; set; }
    }
}
