//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aymk_database.Database
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using System.Runtime.Serialization;
    public partial class CatalogError
    {
        public int id { get; set; }
        public string controller { get; set; }
        public string errorTitle { get; set; }
        public string errorContent { get; set; }
        public string errorType { get; set; }
    }
}
