//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aymk_database.Database
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using System.Runtime.Serialization;
    public partial class CatalogExchange
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatalogExchange()
        {
            this.CatalogMarket = new HashSet<CatalogMarket>();
            this.Exchange = new HashSet<Exchange>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string marketSplitterChar { get; set; }
        public string webSiteUrl { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<bool> active { get; set; }
    
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[JsonIgnore]
        [IgnoreDataMember]
    	    
        public virtual ICollection<CatalogMarket> CatalogMarket { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[JsonIgnore]
        [IgnoreDataMember]
    	    
        public virtual ICollection<Exchange> Exchange { get; set; }
    }
}
