//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aymk_database.Database
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using System.Runtime.Serialization;
    public partial class Log
    {
        public long id { get; set; }
        public int accountId { get; set; }
        public string logType { get; set; }
        public string logContent { get; set; }
        public System.DateTime logDate { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
